apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: go-api
spec:
  # serviceAccountName: go-api
  # automountServiceAccountToken: false
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ca-west-1.amazonaws.com/go-api:v1.28
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
